import { ReactNode } from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { MenuExpandedProvider } from "./hooks/useMenuExpanded";

const poppins = Poppins({ weight: "600", subsets: ['latin']})

export const metadata: Metadata = {
  title: "SmadMovie | Watch in 3D",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`bg-white${poppins.className} bg-zinc_body`}>
        <MenuExpandedProvider>
          {children}
        </MenuExpandedProvider>
      </body>
    </html>
  );
}